import AdminFooter from "@/components/AdminLayout/AdminFooter";
import AdminHeader from "@/components/AdminLayout/AdminHeader";
import ReduxProvider from "@/redux/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import '@/assets/css/style.bundle.css'
import "@/assets/css/plugins/flaticon.css";
import "@/assets/css/plugins/swiper.min.css";
import "@/assets/css/plugins/jquery.fancybox.css";
import "@/assets/css/keenicons/duotone/style.css"
import "@/assets/css/keenicons/outline/style.css"
import "@/assets/css/keenicons/solid/style.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <ToastContainer
                        position="top-center"
                        autoClose={1000}
                        hideProgressBar={true}
                        newestOnTop={false}
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss
                        draggable
                        theme="light"
                    />
                    <AdminHeader />
                    {children}
                    <AdminFooter />
                </ReduxProvider>
            </body>
        </html>
    );
}
