import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "../../assets/css/style.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import ReduxProvider from "@/redux/provider";
import Header from "@/components/Layouts/Header";
import Footer from "@/components/Layouts/Footer";
import MobileHeader from "@/components/Layouts/MobileHeader";
import ShoppingCart from "@/components/ShoppingCart";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ToastContainer
            position="top-center"
            autoClose={1000}
            hideProgressBar={true}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            theme="light"
          />
          <Header/>
          <ShoppingCart/>
          <MobileHeader/>
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
